#!/bin/bash



SRA_DIR="SRA_files"
OUTDIR="fastq_files"

mkdir -p "$OUTDIR"

for folder in "$SRA_DIR"/*; do
    sra=$(echo "$folder"/*.sra)

    if [[ ! -f $sra ]]; then
        echo "Skipping $folder (no SRA file)"
        continue
    fi

    base=$(basename "$folder")

    echo "Processing $sra ..."

    fasterq-dump "$sra" --split-files -O "$OUTDIR"

done

echo "All done!"



